-- 설교 테이블 (sermons)
CREATE TABLE IF NOT EXISTS sermons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  preacher TEXT,
  scripture TEXT,
  series TEXT,
  "videoId" TEXT,
  "youtubeUrl" TEXT
);

-- 뉴스/갤러리 테이블 (news_posts_v3)
CREATE TABLE IF NOT EXISTS news_posts_v3 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT,
  author TEXT,
  date TEXT,
  content TEXT,
  "isPinned" BOOLEAN DEFAULT false,
  file JSONB
);

-- 교회학교 테이블 (school_posts)
CREATE TABLE IF NOT EXISTS school_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  dept TEXT,
  author TEXT,
  date TEXT,
  content TEXT,
  file JSONB
);

-- RLS (Row Level Security) 설정 - 누구나 읽고 쓸 수 있도록 공개 설정 (간단한 연동을 위함)
ALTER TABLE sermons ENABLE ROW LEVEL SECURITY;
ALTER TABLE news_posts_v3 ENABLE ROW LEVEL SECURITY;
ALTER TABLE school_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all read sermons" ON sermons FOR SELECT USING (true);
CREATE POLICY "Allow all insert sermons" ON sermons FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update sermons" ON sermons FOR UPDATE USING (true);
CREATE POLICY "Allow all delete sermons" ON sermons FOR DELETE USING (true);

CREATE POLICY "Allow all read news" ON news_posts_v3 FOR SELECT USING (true);
CREATE POLICY "Allow all insert news" ON news_posts_v3 FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update news" ON news_posts_v3 FOR UPDATE USING (true);
CREATE POLICY "Allow all delete news" ON news_posts_v3 FOR DELETE USING (true);

CREATE POLICY "Allow all read school" ON school_posts FOR SELECT USING (true);
CREATE POLICY "Allow all insert school" ON school_posts FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update school" ON school_posts FOR UPDATE USING (true);
CREATE POLICY "Allow all delete school" ON school_posts FOR DELETE USING (true);
