-- 설교 테이블 (sermons_v2)
CREATE TABLE IF NOT EXISTS sermons_v2 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  preacher TEXT,
  scripture TEXT,
  series TEXT,
  "videoId" TEXT,
  "youtubeUrl" TEXT
);

-- 뉴스/갤러리 테이블 (news_posts_v4)
CREATE TABLE IF NOT EXISTS news_posts_v4 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT,
  author TEXT,
  date TEXT,
  content TEXT,
  "isPinned" BOOLEAN DEFAULT false,
  file JSONB
);

-- 교회학교 테이블 (school_posts_v2)
CREATE TABLE IF NOT EXISTS school_posts_v2 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  dept TEXT,
  author TEXT,
  date TEXT,
  content TEXT,
  file JSONB
);

-- RLS (Row Level Security) 설정 - 누구나 읽고 쓸 수 있도록 공개 설정 (간단한 연동을 위함)
ALTER TABLE sermons_v2 ENABLE ROW LEVEL SECURITY;
ALTER TABLE news_posts_v4 ENABLE ROW LEVEL SECURITY;
ALTER TABLE school_posts_v2 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all read sermons" ON sermons_v2 FOR SELECT USING (true);
CREATE POLICY "Allow all insert sermons" ON sermons_v2 FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update sermons" ON sermons_v2 FOR UPDATE USING (true);
CREATE POLICY "Allow all delete sermons" ON sermons_v2 FOR DELETE USING (true);

CREATE POLICY "Allow all read news" ON news_posts_v4 FOR SELECT USING (true);
CREATE POLICY "Allow all insert news" ON news_posts_v4 FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update news" ON news_posts_v4 FOR UPDATE USING (true);
CREATE POLICY "Allow all delete news" ON news_posts_v4 FOR DELETE USING (true);

CREATE POLICY "Allow all read school" ON school_posts_v2 FOR SELECT USING (true);
CREATE POLICY "Allow all insert school" ON school_posts_v2 FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update school" ON school_posts_v2 FOR UPDATE USING (true);
CREATE POLICY "Allow all delete school" ON school_posts_v2 FOR DELETE USING (true);
